openapi: '3.0.2'
info:
  title: COVID Spain data
  description: 'Información diaria sobre la evolución de la pandemia de COVID-19 en España.'
  version: '1'
servers:
  - url: https://localhost:11223

components:
  parameters:
    autonomous_region:
      in: query
      name: autonomous_region
      description: Filtrar por Comunidad Autónoma. Para obtener solamente los casos de todo el país, usar "España". Si no se especifica este parámetro, se devolverán los datos para cada una de las Comunidades Autónomas y para el país en conjunto.
      schema:
        $ref: '#/components/schemas/AutonomousRegion'
    age_range:
      in: query
      name: age_range
      description: Filtrar por rango de edad. Para los casos de todas las edades, usar "total". Si no se especifica este parámetro, se devolverán los datos para cada uno de los rangos de edad y para todas las edades en conjunto.
      schema:
        $ref: '#/components/schemas/AgeRange'
    gender:
      in: query
      name: gender
      description: Filtrar por sexo. Para los casos de ambos sexos, usar "total". Si no se especifica este parámetro, se devolverán los datos para los hombres, mujeres y en conjunto.
      schema:
        $ref: '#/components/schemas/Gender'
    date:
      in: query
      name: date
      description: Filtrar por fecha. Si no se especifica este parámetro, se devolverán los datos para todos los días desde el 1 de enero de 2020.
      schema:
        type: string
        format: date
        example: '2020-12-30'
        pattern: '\d{4}-d{2}-d{2}'
    response_contents:
      in: query
      name: response_contents
      description: Devuelve solo algunos campos. Si no se especifica este parámetro, se devolverán todos los campos para los datos solicitados.
      schema:
        type: array
        items:
          type: string
          enum: ['new_cases', 'total_cases', 'new_cases_per_population', 'total_cases_per_population', 'ci_last_14_days', 'inverted_ci', 'daily_increase', 'weekly_increase', 'monthly_increase', 'new_cases_ma_1w', 'new_cases_ma_2w']
    limit:
      in: query
      name: limit
      description: Límite de elementos que devolverá la petición.
      schema:
        type: integer
        minimum: 1
    page:
      in: query
      name: page
      description: Número de página si se ha establecido un límite.
      schema:
        type: integer
        minimum: 0
  
  schemas:
    Gender:
      title: Sexo
      type: string
      example: F
      enum:
        - "M"
        - "F"
        - "total"
      description: >
        * `M` - Hombres

        * `F` - Mujeres

        * `total` - Total
        
    AutonomousRegion:
      title: Comunidad Autónoma
      type: string
      example: Galicia
      enum:
        - "España"
        - "Andalucía"
        - "Aragón"
        - "Asturias"
        - "Baleares"
        - "Canarias"
        - "Cantabria"
        - "Castilla y León"
        - "Castilla-La Mancha"
        - "Cataluña"
        - "Ceuta"
        - "Comunidad Valenciana"
        - "Extremadura"
        - "Galicia"
        - "La Rioja"
        - "Madrid"
        - "Melilla"
        - "Murcia"
        - "Navarra"
        - "País Vasco"

    AgeRange:
      title: Rango de edad
      type: string
      example: 20-29
      enum:
        - "0-9"
        - "10-19"
        - "20-29"
        - "30-39"
        - "40-49"
        - "50-59"
        - "60-69"
        - "70-79"
        - "80+"
        - "total"

    endpoints_list:
      title: Lista de endpoints
      type: array
      items:
        type: string
      example: ["/cases", "/deaths", "/hospitalizations"]
    
    daily_cases:
      title: Casos diarios
      type: object
      properties:
        date:
          title: Fecha
          type: string
          format: date
        gender:
          $ref: '#/components/schemas/Gender'
        autonomous_region:
          $ref: '#/components/schemas/AutonomousRegion'
        age_range:
          $ref: '#/components/schemas/AgeRange'
        new_cases:
          type: integer
          description: Número nuevo de casos
          example: 100
        total_cases:
          type: integer
          description: Número de casos acumulados hasta la fecha
          example: 1000
        new_cases_per_population:
          type: number
          description: Número nuevo de casos por cada 100 000 habitantes 
          example: 22.51
        total_cases_per_population:
          type: number
          description: Número de casos acumulados hasta la fecha por cada 100 000 habitantes
          example: 205.11            
        ci_last_14_days:
          type: number
          description: Incidencia acumulada (IA) en los últimos 14 días, es decir, la suma de los casos nuevos registrados en los últimos 14 días por cada 100 000 habitantes
          example: 455.2     
        inverted_ci:
          type: number
          description: Incidencia acumulada en los últimos 14 días invertida. Se trata de una aproximación del número de personas de las cuales, de media, una estaría infectada.
          example: 28.6
        daily_increase:
          type: number
          description: Porcentaje de incremento del número de casos diarios respecto a la media móvil a 7 días del día anterior
          example: 22.1
        weekly_increase:
          type: number
          description: Porcentaje de incremento del número de casos diarios respecto a la media móvil a 14 días de hace 7 días
          example: 65.4            
        monthly_increase:
          type: number
          description: Porcentaje de incremento del número de casos diarios respecto a la media móvil a 60 días de hace 30 días
          example: -11.1           
        new_cases_ma_1w:
          type: number
          description: Media móvil a 7 días del número de casos diarios
          example: 9211.5           
        new_cases_ma_2w:
          type: number
          description: Media móvil a 14 días del número de casos diarios
          example: 9801.1                                               

    daily_deaths:
      title: Fallecimientos diarios
      type: object
      properties:
        date:
          title: Fecha
          type: string
          format: date
        gender:
          $ref: '#/components/schemas/Gender'
        autonomous_region:
          $ref: '#/components/schemas/AutonomousRegion'
        age_range:
          $ref: '#/components/schemas/AgeRange'
        new_deaths:
          type: integer
          description: Número nuevo de fallecimientos
          example: 100
        total_deaths:
          type: integer
          description: Número de muertes acumuladas hasta la fecha
          example: 1000
        new_deaths_per_population:
          type: number
          description: Número nuevo de muertes por cada 100 000 habitantes 
          example: 0.351
        total_deaths_per_population:
          type: number
          description: Número de muertes acumuladas hasta la fecha por cada 100 000 habitantes
          example: 2.11            
        daily_increase:
          type: number
          description: Porcentaje de incremento del número de fallecimientos diarios respecto a la media móvil a 7 días del día anterior
          example: 22.1
        weekly_increase:
          type: number
          description: Porcentaje de incremento del número de fallecimientos diarios respecto a la media móvil a 14 días de hace 7 días
          example: 65.4            
        monthly_increase:
          type: number
          description: Porcentaje de incremento del número de fallecimientos diarios respecto a la media móvil a 60 días de hace 30 días
          example: -11.1           
        new_deaths_ma_1w:
          type: number
          description: Media móvil a 7 días del número de fallecimientos diarios
          example: 92.5           
        new_deaths_ma_2w:
          type: number
          description: Media móvil a 14 días del número de fallecimientos diarios
          example: 98.1    
        mortality_2w:
          type: number
          description: Porcentaje de casos que han acabado en fallecimiento en las últimas 2 semanas
          example: 2.21
        mortality_total:
          type: number
          description: Porcentaje acumulado de casos que han acabado en fallecimiento
          example: 4.22

    hospitalizations:
      title: Hospitalizaciones diarias
      type: object
      properties:
        date:
          title: Fecha
          type: string
          format: date
        gender:
          $ref: '#/components/schemas/Gender'
        autonomous_region:
          $ref: '#/components/schemas/AutonomousRegion'
        age_range:
          $ref: '#/components/schemas/AgeRange'
        new_hospitalizations:
          type: integer
          description: Número nuevo de hospitalizaciones
          example: 100
        total_hospitalizations:
          type: integer
          description: Número de hospitalizaciones acumuladas hasta la fecha
          example: 1000
        new_hospitalizations_per_population:
          type: number
          description: Número nuevo de hospitalizaciones por cada 100 000 habitantes 
          example: 0.351
        total_hospitalizations_per_population:
          type: number
          description: Número de hospitalizaciones acumuladas hasta la fecha por cada 100 000 habitantes
          example: 2.11            
        hospitalizations_daily_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones diarias respecto a la media móvil a 7 días del día anterior
          example: 22.1
        hospitalizations_weekly_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones diarias respecto a la media móvil a 14 días de hace 7 días
          example: 65.4            
        hospitalizations_monthly_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones diarias respecto a la media móvil a 60 días de hace 30 días
          example: -11.1           
        new_hospitalizations_ma_1w:
          type: number
          description: Media móvil a 7 días del número de hospitalizaciones diarias
          example: 92.5           
        new_hospitalizations_ma_2w:
          type: number
          description: Media móvil a 14 días del número de hospitalizaciones diarias
          example: 98.1    
        hospitalizations_ratio_2w:
          type: number
          description: Porcentaje de casos que han requerido hospitalización en las últimas 2 semanas
          example: 2.21
        hospitalizations_ratio_total:
          type: number
          description: Porcentaje acumulado de casos que han requerido hospitalización
          example: 4.22
        new_ic_hospitalizations:
          type: integer
          description: Número nuevo de hospitalizaciones en UCI
          example: 100
        total_ic_hospitalizations:
          type: integer
          description: Número de hospitalizaciones en UCI acumuladas hasta la fecha
          example: 1000
        new_ic_hospitalizations_per_population:
          type: number
          description: Número nuevo de hospitalizaciones en UCI por cada 100 000 habitantes 
          example: 0.351
        total_ic_hospitalizations_per_population:
          type: number
          description: Número de hospitalizaciones en UCI acumuladas hasta la fecha por cada 100 000 habitantes
          example: 2.11            
        hospitalizations_ic_daily_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones en UCI diarias respecto a la media móvil a 7 días del día anterior
          example: 22.1
        hospitalizations_ic_weekly_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones en UCI diarias respecto a la media móvil a 14 días de hace 7 días
          example: 65.4            
        hospitalizations_ic_monthly_increase:
          type: number
          description: Porcentaje de incremento del número de hospitalizaciones en UCI diarias respecto a la media móvil a 60 días de hace 30 días
          example: -11.1           
        new_hospitalizations_ic_ma_1w:
          type: number
          description: Media móvil a 7 días del número de hospitalizaciones en UCI diarias
          example: 92.5           
        new_hospitalizations_ic_ma_2w:
          type: number
          description: Media móvil a 14 días del número de hospitalizaciones en UCI diarias
          example: 98.1    
        hospitalizations_ic_ratio_2w:
          type: number
          description: Porcentaje de casos que han requerido hospitalización en UCI en las últimas 2 semanas
          example: 2.21
        hospitalizations_ic_ratio_total:
          type: number
          description: Porcentaje acumulado de casos que han requerido hospitalización en UCI
          example: 4.22

paths:
  /:
    get:
      summary: Endpoints de la API
      description: Devuelve una lista con todos los endpoints disponibles en esta API
      responses:
        '200':
          description: Lista con todos los endpoints
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/endpoints_list'
              
  /cases:
    get:
      summary: Datos diarios de casos
      description: Datos diarios de los casos de COVID detectados en España, clasificados por Comunidad Autónoma, sexo y rango de edad
      parameters:
        - $ref: '#/components/parameters/autonomous_region'
        - $ref: '#/components/parameters/age_range'
        - $ref: '#/components/parameters/gender'
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/response_contents'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/page'

      responses:
        '200':
          description: Devuelve los datos solicitados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/daily_cases'

  /deaths:
    get:
      summary: Datos diarios de fallecimientos
      description: Datos diarios de los fallecimientos de COVID detectados en España, clasificados por Comunidad Autónoma, sexo y rango de edad
      parameters:
        - $ref: '#/components/parameters/autonomous_region'
        - $ref: '#/components/parameters/age_range'
        - $ref: '#/components/parameters/gender'
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/response_contents'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/page'

      responses:
        '200':
          description: Devuelve los datos solicitados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/daily_deaths'

  /hospitalizations:
    get:
      summary: Datos diarios de hospitalizaciones
      description: Datos diarios de las hospitalizaciones por COVID en España, clasificados por Comunidad Autónoma, sexo y rango de edad
      parameters:
        - $ref: '#/components/parameters/autonomous_region'
        - $ref: '#/components/parameters/age_range'
        - $ref: '#/components/parameters/gender'
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/response_contents'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/page'

      responses:
        '200':
          description: Devuelve los datos solicitados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/daily_hospitalizations'