version: "3.9"
services:
  airflow-backend:
    image: mysql:latest
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    networks: 
      - airflow
    volumes:
      - "airflow-backend:/var/lib/mysql"
    env_file:
      - ./docker/mysql.env
    cap_add:
      - SYS_NICE
    
  airflow-scheduler:
    build: ./docker/airflow
    command: scheduler
    depends_on: 
      - airflow-backend
      - database
    networks: 
      - airflow
    volumes:
      - "airflow-engine:/opt/airflow"
      - "./dags:/opt/airflow/dags"
      - "./covid_data:/home/airflow/covid"
    env_file:
      - ./docker/mysql.env

  airflow-webserver:
    build: ./docker/airflow
    command: webserver
    depends_on: 
      - airflow-backend
      - database
    networks: 
      - airflow
    volumes:
      - "airflow-engine:/opt/airflow"
      - "./dags:/opt/airflow/dags"
      - "./covid_data:/home/airflow/covid"
    ports:
      - "8080:8080"
    env_file:
      - ./docker/mysql.env  

  database:
    build: ./docker/mongodb/
    ports:
      - "12345:27017"
    networks:
      - airflow
      - api
    volumes:
      - "database:/data/db"
    env_file:
      - ./docker/mongodb.env

  rest-api:
    build: "./docker/rest-api"
    ports:
      - "11223:80"
    networks:
      - api
    depends_on:
      - database

networks:
  airflow:
  api:
volumes:
  airflow-backend:
  airflow-engine:
  database: