version: "3.9"
x-redash-service: &redash-service
  build:
    context: ./docker/redash
    args:
      skip_frontend_build: "true"
  volumes:
    - ./docker/redash:/app
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "WARN"
  REDASH_REDIS_URL: "redis://redash-redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@redash-postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
services:
  airflow-backend:
    image: mysql:latest
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    networks: 
      - airflow
    volumes:
      - "airflow-backend:/var/lib/mysql"
    env_file:
      - ./docker/mysql.env
    cap_add:
      - SYS_NICE
    
  airflow-scheduler:
    build: ./docker/airflow
    command: scheduler
    depends_on: 
      - airflow-backend
      - database
    networks: 
      - airflow
    volumes:
      - "airflow-engine:/opt/airflow"
      - "./dags:/opt/airflow/dags"
      - "./covid_data:/home/airflow/covid"
    env_file:
      - ./docker/mysql.env

  airflow-webserver:
    build: ./docker/airflow
    command: webserver
    depends_on: 
      - airflow-backend
      - database
    networks: 
      - airflow
    volumes:
      - "airflow-engine:/opt/airflow"
      - "./dags:/opt/airflow/dags"
      - "./covid_data:/home/airflow/covid"
    ports:
      - "8080:8080"
    env_file:
      - ./docker/mysql.env  

  database:
    build: ./docker/mongodb/
    ports:
      - "12345:27017"
    networks:
      - airflow
      - api
    volumes:
      - "database:/data/db"
    env_file:
      - ./docker/mongodb.env

  rest-api:
    build: "./docker/rest-api"
    ports:
      - "11223:80"
    networks:
      - api
    depends_on:
      - database

  redash-server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - database
      - redash-postgres
      - redash-redis
    ports:
      - "5000:5000"
      - "5678:5678"
    networks:
      - redash
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  redash-scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - redash-server
    networks:
      - redash
    environment:
      <<: *redash-environment
  redash-worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - redash-server
    networks:
      - redash
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  redash-redis:
    image: redis:3-alpine
    restart: unless-stopped
    networks:
      - redash
  redash-postgres:
    build: ./docker/redash-database
    networks:
      - redash
    volumes:
      - redash-postgres
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

networks:
  airflow:
  redash:
  api:
volumes:
  airflow-backend:
  airflow-engine:
  database:
  redash-postgres: