version: "3.8"
x-airflow-service: &airflow-service
  build: ./docker/airflow
  depends_on: 
    - airflow-backend
    - database
  networks: 
    - airflow
  volumes:
    - "airflow-engine:/opt/airflow"
    - "./dags:/opt/airflow/dags"
    - "./covid_data:/home/airflow/covid"
  env_file:
    - ./docker/mysql.env
services:
  airflow-initializer:
    <<: *airflow-service
    entrypoint: bash
    command: -c "airflow db upgrade && airflow connections add --conn-type mongo --conn-description 'Connection to the MongoDB datastore' --conn-host database --conn-login airflow_user --conn-password contrasenha123 --conn-schema covid_admin mongo_covid && airflow users create --username admin --firstname Nombre --lastname Apellido --role Admin --email covid_dashboard@noreply.com --password nonecesitocontrasenha"
    profiles: ["airflow"]
